models/NilaiAkhir.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "nilai_akhir".
 *
 * @property int $id_nilai
 * @property int $id_sekolah
 * @property int $id_siswa
 * @property int $id_mapel
 * @property int $id_semester
 * @property int $id_nilai_kd_keterampilan
 * @property int $id_nilai_kd_pengetahuan
 * @property string $predikat
 * @property string $deskripsi
 * @property string $created_at
 * @property string $updated_at
 *
 * @property NilaiKdKeterampilan $nilaiKdKeterampilan
 * @property NilaiKdPengetahuan $nilaiKdPengetahuan
 */
class NilaiAkhir extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'nilai_akhir';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id_sekolah', 'id_siswa', 'id_mapel', 'id_semester', 'id_nilai_kd'], 'required'],
            [['id_sekolah', 'id_siswa', 'id_mapel', 'id_semester', 'id_nilai_kd','id_kelas'], 'integer'],
            [['nilai_pengetahuan', 'nilai_keterampilan'], 'number'],
            [['predikat_pengetahuan','predikat_keterampilan', 'deskripsi_pengetahuan','deskripsi_keterampilan'], 'string'],
            [['created_at', 'updated_at'], 'safe'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id_nilai' => 'Id Nilai',
            'id_sekolah' => 'Id Sekolah',
            'id_siswa' => 'Id Siswa',
            'id_kelas' => 'Id Kelas',
            'id_mapel' => 'Id Mapel',
            'id_semester' => 'Id Semester',
            'id_nilai_kd' => 'Id Nilai Kd ',
            'nilai_keterampilan' => 'Nilai Keterampilan',
            'nilai_pengetahuan' => 'Nilai Pengetahuan',
            'predikat_pengetahuan' => 'Predikat Pengetahuan',
            'predikat_keterampilan' => 'Predikat Keterampilan',
            'deskripsi_pengetahuan' => 'Deskripsi Pengetahuan',
            'deskripsi_keterampilan' => 'Deskripsi Keterampilan',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * Gets query for [[NilaiKdKeterampilan]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getNilaikdketerampilan()
    {
        return $this->hasOne(NilaiKdKeterampilan::className(), ['id_nilai_kd' => 'id_nilai_kd_keterampilan']);
    }

    /**
     * Gets query for [[NilaiKdPengetahuan]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getNilaikdpengetahuan()
    {
        return $this->hasOne(NilaiKdPengetahuan::className(), ['id_nilai_kd' => 'id_nilai_kd_pengetahuan']);
    }

     public function getSiswa()
    {
        return $this->hasOne(Siswa::className(), ['id_siswa' => 'id_siswa']);
    }
    public function getMapel()
    {
        return $this->hasOne(MataPelajaran::className(), ['id_mapel' => 'id_mapel']);
    }
    public function getSemester()
    {
        return $this->hasOne(Semester::className(), ['id_semester' => 'id_semester']);
    }
     public function getKdpengetahuan()
    {
        return $this->hasOne(KompetensiDasarPengetahuan::className(), ['id_kd_pengetahuan' => 'id_kd_pengetahuan']);
    }
     public function getKdketerampilan()
    {
        return $this->hasOne(KompetensiDasarKeterampilan::className(), ['id_kd_keterampilan' => 'id_kd_keterampilan']);
    }
}

controllers/NilaiAkhirController.php
<?php

namespace app\controllers;

use Yii;
use app\models\NilaiAkhir;
use app\models\NilaiAkhirSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\Sekolah;
use app\models\Siswa;
use kartik\mpdf\Pdf;
use app\models\SikapAkhir;
use app\models\Kehadiran;
use app\models\Prestasi;
use app\models\Esktrakurikuler;
use app\models\Saran;
use app\models\KondisiKesehatan;
use app\models\TinggiBadan;
use app\models\KkmSatuanPendidikan;
use app\models\NilaiKdKeterampilan;
use app\models\Guru;
use app\models\Kelas;
use app\models\NilaiKdPengetahuan;
use app\models\Mengajar;
use app\models\NilaiAkhirKkmSatuanPendidikan;
/**
 * NilaiAkhirController implements the CRUD actions for NilaiAkhir model.
 */
class NilaiAkhirController extends Controller
{
     public $layout = "backend.php";
    /**
     * {@inheritdoc}
     */
     public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
            'access' => [
                        'class' => \yii\filters\AccessControl::className(),
                        'only' => ['index','create','update','view'],
                        'rules' => [
                            // allow authenticated users
                            [
                                'allow' => true,
                                'roles' => ['@'],
                            ],
                            // everything else is denied
                        ],
                    ],            
        ];
    }

    /**
     * Lists all NilaiAkhir models.
     * @return mixed
     */
    public function actionIndex()
    {
        $sekolah = Sekolah::find()->where(['id_user' => Yii::$app->user->identity->id_user])->one();
        if (Yii::$app->user->identity->role=="Administrator") {
            $searchModel = new NilaiAkhirSearch(['id_sekolah' => $sekolah->id_sekolah]);
        }elseif (Yii::$app->user->identity->role=="Guru") {
            $guru = Guru::find()->where(['id_user' => Yii::$app->user->identity->id_user])->one();
                $kelas = Kelas::find()->where(['id_guru' => $guru->id_guru])->one();
                $mengajar = Mengajar::find()->where(['id_guru' => $guru->id_guru])->one();
                
                if ($kelas) {
                    $searchModel = new NilaiAkhirSearch(['id_kelas' => $kelas->id_kelas]);
                }elseif ($mengajar){
                    $mapel = Mengajar::find()->where(['id_mapel' => $mengajar->id_mapel])->one();
                    $searchModel = new NilaiAkhirSearch(['id_mapel' => $mapel->id_mapel]);
                }else{
                    $searchModel = new NilaiAkhirSearch();
                }
        }else{
            $siswa = Siswa::find()->where(['id_user' => Yii::$app->user->identity->id_user])->one();
            $searchModel = new NilaiAkhirSearch(['id_siswa' => $siswa->id_siswa]);
        }
        
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionSearch()
    {
        $sekolah = Sekolah::find()->where(['id_user' => Yii::$app->user->identity->id_user])->one();
        if (Yii::$app->user->identity->role=="Administrator") {
            $searchModel = new NilaiAkhirSearch(['id_sekolah' => $sekolah->id_sekolah]);
        }elseif (Yii::$app->user->identity->role=="Guru") {
            $guru = Guru::find()->where(['id_user' => Yii::$app->user->identity->id_user])->one();
                $kelas = Kelas::find()->where(['id_guru' => $guru->id_guru])->one();
                $mengajar = Mengajar::find()->where(['id_guru' => $guru->id_guru])->one();
                
                if ($kelas) {
                    $searchModel = new NilaiAkhirSearch(['id_kelas' => $kelas->id_kelas]);
                }elseif ($mengajar){
                    $mapel = Mengajar::find()->where(['id_mapel' => $mengajar->id_mapel])->one();
                    $searchModel = new NilaiAkhirSearch(['id_mapel' => $mapel->id_mapel]);
                }else{
                    $searchModel = new NilaiAkhirSearch();
                }
        }else{
            $siswa = Siswa::find()->where(['id_user' => Yii::$app->user->identity->id_user])->one();
            $searchModel = new NilaiAkhirSearch(['id_siswa' => $siswa->id_siswa]);
        }
        
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->renderAjax('_search', [
            'model' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionLihatsiswa($id)
    {
        $searchModel = new NilaiAkhirSearch(['id_siswa' => $id]);
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionPilihsiswa()
    {
        return $this->render('pilihsiswa');
    }
    public function actionPilih()
    {
        return $this->render('pilih');
    }
    public function actionPrintraport($id_siswa)
    {
        $modelA = NilaiAkhir::find()->where(['id_siswa' => $id_siswa])->joinWith('mapel')->where(['id_siswa' => $id_siswa, 'kelompok' => 'A'])->all();
        $modelB = NilaiAkhir::find()->where(['id_siswa' => $id_siswa])->joinWith('mapel')->where(['id_siswa' => $id_siswa, 'kelompok' => 'B'])->all();
        $modelC = NilaiAkhir::find()->where(['id_siswa' => $id_siswa])->joinWith('mapel')->where(['id_siswa' => $id_siswa, 'kelompok' => 'C'])->all();

        $siswa = Siswa::find()->where(['id_siswa' => $id_siswa])->all();
        $pesertadidik = Siswa::find()->where(['id_siswa' => $id_siswa])->one();
        $sekolah = Sekolah::find()->where(['id_sekolah' => $pesertadidik->id_sekolah])->all();
        $nilaisikap = SikapAkhir::find()->where(['id_siswa' => $id_siswa])->all();
        $ekskul = Esktrakurikuler::find()->where(['id_siswa' => $id_siswa, 'id_kelas' => $pesertadidik->id_kelas, 'id_semester' => $pesertadidik->id_semester])->all();
        $kehadiran = Kehadiran::find()->where(['id_siswa' => $id_siswa, 'id_kelas' => $pesertadidik->id_kelas, 'id_semester' => $pesertadidik->id_semester])->all();
        $prestasi = Prestasi::find()->where(['id_siswa' => $id_siswa, 'id_kelas' => $pesertadidik->id_kelas, 'id_semester' => $pesertadidik->id_semester])->all();
        $saran = Saran::find()->where(['id_siswa' => $id_siswa, 'id_kelas' => $pesertadidik->id_kelas, 'id_semester' => $pesertadidik->id_semester])->all();
        $kondisikesehatan = KondisiKesehatan::find()->where(['id_siswa' => $id_siswa, 'id_kelas' => $pesertadidik->id_kelas, 'id_semester' => $pesertadidik->id_semester])->all();
        $tinggibadan = TinggiBadan::find()->where(['id_siswa' => $id_siswa, 'id_kelas' => $pesertadidik->id_kelas, 'id_semester' => $pesertadidik->id_semester])->all();

        $content = $this->renderPartial('raport',[
            'modelA' => $modelA,
            'modelB' => $modelB,
            'modelC' => $modelC,
            'sekolah' => $sekolah,
            'siswa' => $siswa,
            'nilaisikap' => $nilaisikap,
            'pesertadidik' => $pesertadidik,
            'ekskul' => $ekskul,
            'kehadiran' => $kehadiran,
            'saran' => $saran,
            'kondisikesehatan' => $kondisikesehatan,
            'prestasi' => $prestasi,
            'tinggibadan' => $tinggibadan,
        ]);
    
        // setup kartik\mpdf\Pdf component
        $pdf = new Pdf([
            // set to use core fonts only
            'mode' => Pdf::MODE_CORE, 
            // A4 paper format
            'format' => Pdf::FORMAT_A4, 
            // portrait orientation
            'orientation' => Pdf::ORIENT_PORTRAIT, 
            // stream to browser inline
            'destination' => Pdf::DEST_BROWSER, 
            'filename' => 'test.pdf',
            // your html content input
            'content' => $content,  
            // format content from your own css file if needed or use the
            // enhanced bootstrap css built by Krajee for mPDF formatting 
            'cssFile' => '@vendor/kartik-v/yii2-mpdf/src/assets/kv-mpdf-bootstrap.min.css',
            // any css to be embedded if required
            'cssInline' => '.kv-heading-1{font-size:18px}', 
             // set mPDF properties on the fly
            'options' => ['title' => 'Krajee Report Title'],
            // 'marginLeft' => 5, 'marginTop' => 5, 'marginRight' => 5, 'marginBottom' => 5,
            'defaultFont' => 'Calibri',
             // call mPDF methods on the fly
            'methods' => [ 
                'SetHeader'=>['Krajee Report Header'], 
                'SetFooter' => ['raport sd'],
                'SetFooter'=>['{PAGENO}'],
            ]
        ]);
        
        // return the pdf output as per the destination setting
        return $pdf->render();
       
        
    }

    public function actionKkmsatuanpendidikan()
    {
        $searchModel = new NilaiAkhirSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('kkm_satuan_pendidikan', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider
        ]);
    }

    public function actionRangking()
    {
        $sekolah = Sekolah::find()->where(['id_user' => Yii::$app->user->identity->id_user])->one();
        if (Yii::$app->user->identity->role=="Administrator") {
            $searchModel = new NilaiAkhirSearch(['id_sekolah' => $sekolah->id_sekolah]);
        }elseif (Yii::$app->user->identity->role=="Guru") {

views/nilai-akhir/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\NilaiAkhir */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="nilai-akhir-form">

    <?php $form = ActiveForm::begin(); ?>

   


    <?= $form->field($model, 'deskripsi_pengetahuan')->textarea(['rows' => 4]) ?>
    <?= $form->field($model, 'deskripsi_keterampilan')->textarea(['rows' => 4]) ?>

    <div class="form-group" style="float: right;">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/nilai-akhir/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\NilaiAkhir */

$this->title = 'Create Nilai Akhir';
$this->params['breadcrumbs'][] = ['label' => 'Nilai Akhirs', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="nilai-akhir-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/nilai-akhir/index.php
<?php

use yii\helpers\Html;
use kartik\grid\GridView;
use yii\helpers\Url;
use app\models\Guru;
use app\models\Siswa;
use app\models\NilaiKdPengetahuan;
use app\models\NilaiKdKeterampilan;
use app\models\KompetensiDasarPengetahuan;
use kartik\form\ActiveForm;
use app\models\KompetensiDasarKeterampilan;
use app\models\SdNilaiHarianPengetahuan;
use app\models\SdNilaiHarianKeterampilan;
use app\models\MataPelajaran;
use app\models\Kelas;
use app\models\BobotPenilaian;
use app\models\KkmSatuanPendidikan;
use app\models\Mengajar;
use app\models\Sekolah; 
/* @var $this yii\web\View */
/* @var $searchModel app\models\GuruSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Nilai Akhir (Multi KKM)';
$this->params['breadcrumbs'][] = $this->title;
?>
<section class="content">
      <div class="row">
        <div class="col-xs-12">
          <div class="box">
            
            <!-- /.box-header -->
            <div class="box-body">
    <h2><?= Html::encode($this->title) ;?></h2>
    <?php if(Yii::$app->user->identity->role=="Administrator" || Yii::$app->user->identity->role=="Guru"){ ?>
            <p>
                <?= Html::a('<span class="fa fa-print"></span> Cetak Raport',['pilihsiswa'],
                        ['title' => '', 'class' => 'btn btn-info', 'target' => '_blank'
                    ]);
                    ?>
                <?= Html::a('<span class="fa fa-print"></span> Rangking',['rangking/create'],
                        ['title' => '', 'class' => 'btn btn-warning', 'target' => '_blank'
                    ]);
                    ?>
                <?= Html::button('Cetak Rapor',
                                    ['value' => Url::to(['nilai-akhir/pilihsiswa']),
                                    'title' => '', 'class' => 'showModalButton btn btn-info']); 
                ?>
                <?php
                if(Yii::$app->user->identity->role=="Administrator"){
                    $sekolah = Sekolah::find()->where(['id_user' => Yii::$app->user->identity->id_user])->one();
                    $kelas = Kelas::find()->where(['id_sekolah' => $sekolah->id_sekolah])->one();
                    $bobot = KkmSatuanPendidikan::find()->where(['id_kelas' => $kelas->id_kelas])->one();
                }else{
                    $guru = Guru::find()->where(['id_user' => Yii::$app->user->identity->id_user])->one();
                    $mengajar = Mengajar::find()->where(['id_guru' => $guru->id_guru])->one();
                    $kelas = Kelas::find()->where(['id_guru' => $guru->id_guru])->one();
                    
                    if ($kelas) {
                        $bobot = KkmSatuanPendidikan::find()->where(['id_kelas' => $kelas->id_kelas])->one();
                    }elseif ($mengajar){
                        $mapel = Mengajar::find()->where(['id_mapel' => $mengajar->id_mapel])->one();
                        $bobot = KkmSatuanPendidikan::find()->where(['id_kelas' => $mapel->id_kelas])->one();
                    }
                }
                if($bobot){
                    if(Yii::$app->user->identity->role=="Administrator"){
                        $sekolah = Sekolah::find()->where(['id_user' => Yii::$app->user->identity->id_user])->one();
                        if($sekolah->jenjang_pendidikan == 'SD'){ ?>
                            <?= Html::a('<span class="fa fa-print"></span> KKM Satuan Pendidikan',['nilai-akhir-kkm-satuan-pendidikan/create'],
                            ['title' => '', 'class' => 'btn btn-success', 'data-confirm' => 'Nilai akhir ini menggunakan kkm satuan pendidikan','target' => '_blank'
                            ]);
                            ?>
                        <?php } else{ ?>
                            <?= Html::a('<span class="fa fa-print"></span> KKM Satuan Pendidikan',['nilai-akhir-kkm-satuan-pendidikan/createsekolahmenengah'],
                            ['title' => '', 'class' => 'btn btn-success', 'data-confirm' => 'Nilai akhir ini menggunakan kkm satuan pendidikan','target' => '_blank'
                            ]);
                            ?>
                        <?php } }else{ 
                            $guru = Guru::find()->where(['id_user' => Yii::$app->user->identity->id_user])->one();
                            if($guru->tblsekolah->jenjang_pendidikan == 'SD'){ ?>
                                <?= Html::a('<span class="fa fa-print"></span> KKM Satuan Pendidikan',['nilai-akhir-kkm-satuan-pendidikan/create'],
                                ['title' => '', 'class' => 'btn btn-success', 'data-confirm' => 'Nilai akhir ini menggunakan kkm satuan pendidikan','target' => '_blank'
                                ]);
                                ?>
                        <?php } else{ ?>
                                <?= Html::a('<span class="fa fa-print"></span> KKM Satuan Pendidikan',['nilai-akhir-kkm-satuan-pendidikan/createsekolahmenengah'],
                                ['title' => '', 'class' => 'btn btn-success', 'data-confirm' => 'Nilai akhir ini menggunakan kkm satuan pendidikan','target' => '_blank'
                                ]);
                                ?>
                        <?php }
                        }
                ?>
                   
                <?php }else{ ?>
                    <button class="btn btn-default" onClick="return alert('KKM satuan pendidikan belum dibuat')">KKM Satuan Pendidikan</button>
                <?php } ?>               
            </p>
    <?php }else{ ?>
            <p>
                
            </p>
    <?php } ?>  

    <?php $form = ActiveForm::begin(); ?>
    
    <?= GridView::widget([
    'dataProvider' => $dataProvider,
    //'filterModel' => $searchModel,
     'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            //'id_nilai',
            //'id_sekolah',
            // [
            //     'attribute' => 'id_siswa',
            //     'label' => 'Siswa',
            //     'value' => function($model){
            //         return $model->siswa->nama;
            //     }
            // ],
           [
                'attribute' => 'id_mapel',
                'label' => 'Mata Pelajaran',
                'value' => function($model){
                    return $model->mapel->nama_mata_pelajaran;
                }
            ],


            //'id_semester',
           //'id_nilai_kd',
            [
                'attribute' => 'nilai_pengetahuan',
                'label' => 'Nilai',
                'value' => function($model){
                    return $model->nilai_pengetahuan;
                }
            ],
            [
                'attribute' => 'predikat_pengetahuan',
                'label' => 'Predikat',
                'value' => function($model){
                    return $model->predikat_pengetahuan;
                }
            ],
            [
                'attribute' => 'deskripsi_pengetahuan',
                'label' => 'Deskripsi Pengetahuan',
                'format' => 'html',
                'value' => function($model){
                   return $model->deskripsi_pengetahuan;                    
                }
            ],
           [
                'attribute' => 'nilai_keterampilan',
                'label' => 'Nilai',
                'value' => function($model){
                    return $model->nilai_keterampilan;
                }
            ],
           [
                'attribute' => 'predikat_keterampilan',
                'label' => 'Predikat',
                'value' => function($model){
                    return $model->predikat_keterampilan;
                }
            ],
           [
                'attribute' => 'deskripsi_keterampilan',
                'label' => 'Deskripsi Keterampilan',
                'format' => 'html',
                'value' => function($model){
                    return $model->deskripsi_keterampilan;
                   
                }
            ],
           
            ['class' => 'yii\grid\ActionColumn',
            'visibleButtons' => [
                'update' => false,
                'delete' => false,
            ],
            'buttons' => [
                  'view' => function($url,$model){
                    
                        $a = Html::button('<span class="fa fa-eye"></span>',
                            ['value' => Url::to(['view','id'=>$model->id_nilai]),
                            'title' => '', 'class' => 'showModalButton btn btn-info']);
                        $b = Html::button('<span class="fa fa-pencil"></span> Deskripsi Manual',
                        ['value' => Url::to(['update','id'=>$model->id_nilai]),
                        'title' => '', 'class' => 'showModalButton btn btn-info']);
                        $c = "<button class='btn btn-default btn-block' onClick='return alert('Deskripsi masih kosong')'><span class='fa fa-pencil'></span> Deskripsi Manual</button>";
                       
                       
                        if(Yii::$app->user->identity->role=="Administrator" || Yii::$app->user->identity->role=="Guru" ){
                            if ($model->deskripsi_pengetahuan == NULL || $model->deskripsi_keterampilan == NULL) {
                                return $c;
                            }else{
                                return $b;
                            }
                            
                        }else{
                            return $a;
                        }
                        
                    
                        
                    }
            ],
            

    
    ],

    [
                'class' => 'kartik\grid\CheckboxColumn',
                'header' => Html::a('<span class="fa fa-trash"></span>', ['deleteall'],['data-method' => 'POST',  'data-confirm' => 'Are you sure you want to delete this item?' ,'class' => 'btn  btn-danger']),
                'name' => 'hapus',
            ],
        
        
        ],
    'containerOptions' => ['style'=>'overflow: auto'], // only set when $responsive = false
    'beforeHeader'=>[
        [
            // 'columns'=>[
            //     ['content'=>'Header Before 1', 'options'=>['colspan'=>4, 'class'=>'text-center warning']], 
            //     ['content'=>'Header Before 2', 'options'=>['colspan'=>4, 'class'=>'text-center warning']], 
            //     ['content'=>'Header Before 3', 'options'=>['colspan'=>3, 'class'=>'text-center warning']], 
            // ],
            'options'=>['class'=>'skip-export'] // remove this row from export
        ]
    ],
    'toolbar' =>  [
         ['content'=>
                 Html::button('Search', [
                'value' => Url::to(['search']), 
                'class' => 'showModalButton btn btn-default',
                'style' => 'float:left',
        ]).''.
        //     Html::button('&lt;i class="glyphicon glyphicon-plus">&lt;/i>', ['type'=>'button', 'title'=>Yii::t('kvgrid', 'Add Book'), 'class'=>'btn btn-success', 'onclick'=>'alert("This will launch the book creation form.\n\nDisabled for this demo!");']) . ' '.
        Html::a('<span class="fa fa-repeat"></span>', ['index'], ['data-pjax'=>0, 'class' => 'btn btn-default', 'style' => 'margin-left:5px;'])
         ],
        '{export}',
        '{toggleData}'
    ],
    'pjax' => true,
    'bordered' => true,
    'striped' => true,
    'condensed' => true,
    'responsive' => true,
    'hover' => true,
    'floatHeader' => true,
   // 'floatHeaderOptions' => ['top' => $scrollingTop],
    'showPageSummary' => true,
    'panel' => [
        'type' => GridView::TYPE_INFO
    ],
]);
ActiveForm::end();
?>
</div>
</div>
</div>
</div>
</section>


<?php
yii\bootstrap\Modal::begin([
'headerOptions' => ['id' => 'modalHeader'],
'id' => 'modal',
'size' => 'modal-default',
'clientOptions' => ['backdrop' => 'static', 'keyboard' => true]
]);
echo "<div id='modalContent'></div>";
 echo '<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>';
yii\bootstrap\Modal::end();
?>

views/nilai-akhir/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\NilaiAkhir */

$this->title = 'Update Nilai Akhir: ' . $model->id_nilai;
$this->params['breadcrumbs'][] = ['label' => 'Nilai Akhirs', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id_nilai, 'url' => ['view', 'id' => $model->id_nilai]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="nilai-akhir-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>