models/Sekolah.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "sekolah".
 *
 * @property int $id_sekolah
 * @property string $nama_sekolah
 * @property string $nama_kepala_sekolah
 * @property string $jenjang_pendidikan
 * @property string $alamat
 * @property string $kelurahan
 * @property string $kecamatan
 * @property string $kabupaten/kota
 * @property string $provinsi
 * @property string $telepon
 */
class Sekolah extends \yii\db\ActiveRecord
{
    public $fotosekolah;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'sekolah';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id_user'], 'required'],
            [['jenjang_pendidikan', 'alamat', 'kelurahan'], 'string'],
            [['id_user'], 'integer'],
            [['nama_sekolah', 'nama_kepala_sekolah','foto', 'kecamatan','npsn', 'kabupaten', 'provinsi','nip_kepsek'], 'string', 'max' => 200],
            [['telepon'], 'string', 'max' => 20],
            [['fotosekolah'], 'file','skipOnEmpty' => true, 'extensions' => 'jpg, jpeg, png'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id_sekolah' => 'Id Sekolah',
            'id_user' => 'Id User',
            'nama_sekolah' => 'Nama Sekolah',
            'nama_kepala_sekolah' => 'Nama Kepala Sekolah',
            'nip_kepsek' => 'Nip Kepsek',
            'jenjang_pendidikan' => 'Jenjang Pendidikan',
            'npsn' => 'NPSN',
            'alamat' => 'Alamat',
            'foto' => 'Foto',
            'kelurahan' => 'Kelurahan',
            'kecamatan' => 'Kecamatan',
            'kabupaten' => 'Kabupaten',
            'provinsi' => 'Provinsi',
            'telepon' => 'Telepon',
        ];
    }
    public function getIdUser()
    {
        return $this->hasOne(User::className(), ['id_user' => 'id_user']);
    }
}

controllers/SekolahController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Sekolah;
use app\models\SekolahSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\Guru;
use app\models\Siswa;
use app\models\User;
use yii\web\UploadedFile;
/**
 * SekolahController implements the CRUD actions for Sekolah model.
 */
class SekolahController extends Controller
{
    public $layout = "backend.php";
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
            'access' => [
                        'class' => \yii\filters\AccessControl::className(),
                        'only' => ['index','create','update','view'],
                        'rules' => [
                            // allow authenticated users
                            [
                                'allow' => true,
                                'roles' => ['@'],
                            ],
                            // everything else is denied
                        ],
                    ],            
        ];
    }


    /**
     * Lists all Sekolah models.
     * @return mixed
     */
    public function actionIndex()
    {
       return $this->render('index');
    }

    /**
     * Displays a single Sekolah model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->renderAjax('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Sekolah model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */

    public function actionCreate()
    {
        $model = new Sekolah();

        if ($model->load(Yii::$app->request->post())) {
            $model->id_user = Yii::$app->user->identity->id_user;
            $tmp = UploadedFile::getInstance($model, 'fotosekolah');
            if ($tmp != NULL) {
                $model->foto = $tmp->baseName.'.'.$tmp->extension;
            }
            
            $model->save();
            if ($tmp != NULL) {
                $tmp->saveAs('foto_sekolah/'.$model->foto);
            }
            
            return $this->redirect(['index']);
        }

        return $this->renderAjax('_form', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Sekolah model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate()
    {
        $model = Sekolah::find()->where(['id_user' => Yii::$app->user->identity->id_user])->one();
        if(Yii::$app->user->identity->role == 'Administrator'){
            if ($model->load(Yii::$app->request->post())) {
                $tmp = UploadedFile::getInstance($model, 'fotosekolah');
                if ($tmp != NULL) {
                    $model->foto = $tmp->baseName.'.'.$tmp->extension;
                }

                $model->save();
                if ($tmp != NULL) {
                    $tmp->saveAs('foto_sekolah/'.$model->foto);
                }
            return $this->redirect(['index']);
            }
        }else{
            return "<script>alert('Gagal... Anda bukan Administrator'); window.location = '".Yii::$app->urlManager->createUrl(['sekolah'])."'</script>";
        }
        
        return $this->render('_form', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Sekolah model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();
        return $this->redirect(['index']);
    }

    /**
     * Finds the Sekolah model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Sekolah the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    
    protected function findModel($id)
    {
        if (($model = Sekolah::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/sekolah/_form.php
<?php

use yii\helpers\Html;
use kartik\form\ActiveForm;
use kartik\select2\Select2;
use kartik\file\FileInput;
use kartik\form\ActiveField;
/* @var $this yii\web\View */
/* @var $model app\models\Sekolah */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="sekolah-form">

    <?php $form = ActiveForm::begin([
        'action' => ['update']
    ]); ?>

    <?= $form->field($model, 'nama_sekolah')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'npsn')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'nama_kepala_sekolah')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'nip_kepsek')->textInput(['maxlength' => true]) ?>
    
    <?= $form->field($model, 'jenjang_pendidikan')->widget(Select2::classname(),[
            'data' => [ 'SD' => 'SD', 'SMP' => 'SMP', 'SMA' => 'SMA', ],
            'language' => 'de',
            'options' => ['placeholder' => 'Pilih sekolah'],
            'pluginOptions' => [
                'allowClear' => true
            ],
        ]) ?>

    <?= $form->field($model, 'alamat', [
    'hintType' => ActiveField::HINT_SPECIAL,
    'hintSettings' => ['placement' => 'right', 'onLabelClick' => true, 'onLabelHover' => false]
        ])->textArea([
            'id' => 'address-input', 
            'placeholder' => 'Enter address...', 
            'rows' => 2
        ])->hint('Enter address in 4 lines. First 2 lines must contain the street details and next 2 lines the city, zip, and country detail.') ?>

    <?= $form->field($model, 'kelurahan')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'kecamatan')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'kabupaten')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'provinsi')->textInput(['maxlength' => true]) ?>
    
    <?= $form->field($model, 'telepon', [
    'feedbackIcon' => [
        'prefix' => 'fas fa-',
        'default' => 'mobile-alt',
        'success' => 'check-circle',
        'error' => 'exclamation-circle',
    ]
    ])->widget('yii\widgets\MaskedInput', [
        'mask' => '9999-9999-9999'
    ]);?>

    <?= $form->field($model, 'fotosekolah')->widget(FileInput::classname(), [
                'options' => ['accept' => 'image/*'],
        ])->label('Foto Sekolah'); ?> 
    
    <?php
    if (Yii::$app->user->identity->role=="Administrator") {?>
    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>
    <?php }else{ ?>
        -
    <?php } ?>

    <?php ActiveForm::end(); ?>

</div>

views/sekolah/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\SekolahSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="sekolah-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id_sekolah') ?>

    <?= $form->field($model, 'nama_sekolah') ?>

    <?= $form->field($model, 'nama_kepala_sekolah') ?>

    <?= $form->field($model, 'jenjang_pendidikan') ?>

    <?= $form->field($model, 'alamat') ?>

    <?php // echo $form->field($model, 'kelurahan') ?>

    <?php // echo $form->field($model, 'kecamatan') ?>

    <?php // echo $form->field($model, 'kabupaten/kota') ?>

    <?php // echo $form->field($model, 'provinsi') ?>

    <?php // echo $form->field($model, 'telepon') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/sekolah/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Sekolah */

$this->title = 'Create Sekolah';
$this->params['breadcrumbs'][] = ['label' => 'Sekolahs', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="sekolah-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/sekolah/index.php
<?php

use yii\helpers\Html;
use kartik\grid\GridView;
use app\models\Sekolah;
use app\models\User;
use yii\helpers\Url;
use app\models\Guru;
use app\models\Siswa;
/* @var $this yii\web\View */
/* @var $searchModel app\models\SekolahSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
$this->title = 'Sekolah';
$this->params['breadcrumbs'][] = $this->title;
?>
<?php
if (Yii::$app->user->identity->role=="Administrator") {
    $user = Sekolah::find()->where(['id_user' => Yii::$app->user->identity->id_user])->one();
    $model = Sekolah::find()->where(['id_sekolah' => $user->id_sekolah])->one();
    $siswa = Siswa::find()->where(['id_sekolah' => $model->id_sekolah])->all();
    $jmlguru = Guru::find()->where(['id_sekolah' => $model->id_sekolah])->all();
}elseif (Yii::$app->user->identity->role=="Guru") {
    $guru = Guru::find()->where(['id_user' => Yii::$app->user->identity->id_user])->one();
    $model = Sekolah::find()->where(['id_sekolah' => $guru->id_sekolah])->one();
    $siswa = Siswa::find()->where(['id_sekolah' => $model->id_sekolah])->all();
    $jmlguru = Guru::find()->where(['id_sekolah' => $model->id_sekolah])->all();
}else{
    $siswa = Siswa::find()->where(['id_user' => Yii::$app->user->identity->id_user])->one();
    $model = Sekolah::find()->where(['id_sekolah' => $siswa->id_sekolah])->one();
    $siswa = Siswa::find()->where(['id_sekolah' => $model->id_sekolah])->all();
    $jmlguru = Guru::find()->where(['id_sekolah' => $model->id_sekolah])->all();
}


?>
<section class="content">
<div class="row">
  <div class="col-md-4">

    <!-- Profile Image -->
    <div class="box box-info">
      <div class="box-body box-profile">
            <img class="profile-user-img img-responsive img-circle" src="foto_sekolah/<?= $model->foto ?>" alt="User profile picture">
        <h4 class="profile-username text-center"><?= $model->nama_sekolah ?></h4>

        <p class="text-muted text-center"><?= $model->nama_kepala_sekolah ?></p>

        <ul class="list-group list-group-unbordered">
          <li class="list-group-item">
            <b>Npsn</b> <a class="pull-right"><?= $model->npsn ?></a>
          </li>
          <li class="list-group-item">
            <b>Nip Kepsek</b> <a class="pull-right"><?= $model->nip_kepsek ?></a>
          </li>
          <li class="list-group-item">
            <b>Email Sekolah</b> <a class="pull-right"><?= $model->idUser->email ?></a>
          </li>
          <li class="list-group-item">
            <b>Jenjang Pendidikan</b> <a class="pull-right"><?= $model->jenjang_pendidikan ?></a>
          </li>
          <li class="list-group-item">
            <b>Jumlah Siswa</b> <a class="pull-right"><?= count($siswa) ?></a>
          </li>
          <li class="list-group-item">
            <b>Jumlah Guru</b> <a class="pull-right"><?= count($jmlguru) ?></a>
          </li>
        </ul>

        <button class="showModalButton btn btn-info" value="<?= Yii::$app->urlManager->createUrl(['sekolah/view', 'id' => $model->id_sekolah]) ?>" style="width:100%;" title=""><b>View</b></button>
      </div>
      <!-- /.box-body -->
    </div>
    <!-- /.box -->

    <!-- About Me Box -->
   
  </div>
  <!-- /.col -->
  <div class="col-md-8">
  <div class="box box-info">
    <div class="nav-tabs-custom">
     
      <div class="tab-content">
       
        <div class="active tab-pane">
        <?php  echo $this->render('update', ['model' => $model]); ?>
        </div>
        <!-- /.tab-pane -->
      </div>
      <!-- /.tab-content -->
    </div>
    <!-- /.nav-tabs-custom -->
  </div>
  <!-- /.col -->
</div>
<!-- /.row -->

</section>

<?php
yii\bootstrap\Modal::begin([
'headerOptions' => ['id' => 'modalHeader'],
'id' => 'modal',
'size' => 'modal-default',
'clientOptions' => ['backdrop' => 'static', 'keyboard' => true]
]);
echo "<div id='modalContent'></div>";
 echo '<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>';
yii\bootstrap\Modal::end();
?>

views/sekolah/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Sekolah */

$this->params['breadcrumbs'][] = ['label' => 'Sekolah', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id_sekolah, 'url' => ['view', 'id' => $model->id_sekolah]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="sekolah-update">


    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/sekolah/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Sekolah */

$this->params['breadcrumbs'][] = ['label' => 'Sekolahs', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="sekolah-view">

    <h1><?= Html::encode($this->title) ?></h1>

    
    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id_sekolah',
            'id_user',
            'nama_sekolah',
            'nip_kepsek',
            'npsn',
            'nama_kepala_sekolah',
            'jenjang_pendidikan',
            'alamat:ntext',
            'kelurahan:ntext',
            'kecamatan',
            'kabupaten',
            'provinsi',
            'telepon',
             [
                'attribute' => 'foto',
                'label' => 'Foto',
                'format' => 'raw',
                'value' => function($model){
                    return Html::img('foto_sekolah/'.$model->foto, ['width' => '50px', 'height' => '50px']);
                }
            ],
        ],
    ]) ?>

</div>