models/RombonganBelajar.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "rombongan_belajar".
 *
 * @property int $id_rombel
 * @property int $id_sekolah
 * @property int $id_kelas
 * @property int $id_semester
 * @property int $tahun_ajaran
 * @property int $id_siswa
 * @property string $created_at
 * @property string $updated_at
 *
 * @property Sekolah $sekolah
 * @property Kelas $kelas
 * @property Siswa $siswa
 * @property Semester $semester
 */
class RombonganBelajar extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'rombongan_belajar';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [[ 'id_kelas'], 'required'],
            [['id_sekolah', 'id_kelas', 'id_semester', 'tahun_ajaran', 'id_siswa','id_guru'], 'integer'],
            [['created_at', 'updated_at','status'], 'safe'],
            [['id_sekolah'], 'exist', 'skipOnError' => true, 'targetClass' => Sekolah::className(), 'targetAttribute' => ['id_sekolah' => 'id_sekolah']],
            [['id_kelas'], 'exist', 'skipOnError' => true, 'targetClass' => Kelas::className(), 'targetAttribute' => ['id_kelas' => 'id_kelas']],
            [['id_siswa'], 'exist', 'skipOnError' => true, 'targetClass' => Siswa::className(), 'targetAttribute' => ['id_siswa' => 'id_siswa']],
            [['id_semester'], 'exist', 'skipOnError' => true, 'targetClass' => Semester::className(), 'targetAttribute' => ['id_semester' => 'id_semester']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id_rombel' => 'Id Rombel',
            'id_sekolah' => 'Id Sekolah',
            'id_kelas' => 'Id Kelas',
            'id_semester' => 'Id Semester',
            'tahun_ajaran' => 'Tahun Ajaran',
            'id_guru' => 'Id Guru',
            'id_siswa' => 'Id Siswa',
            'status' => 'Status',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * Gets query for [[Sekolah]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getSekolah()
    {
        return $this->hasOne(Sekolah::className(), ['id_sekolah' => 'id_sekolah']);
    }

    /**
     * Gets query for [[Kelas]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getKelas()
    {
        return $this->hasOne(Kelas::className(), ['id_kelas' => 'id_kelas']);
    }

    /**
     * Gets query for [[Siswa]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getSiswa()
    {
        return $this->hasOne(Siswa::className(), ['id_siswa' => 'id_siswa']);
    }

    /**
     * Gets query for [[Semester]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getSemester()
    {
        return $this->hasOne(Semester::className(), ['id_semester' => 'id_semester']);
    }
    public function getGuru()
    {
        return $this->hasOne(Guru::className(), ['id_guru' => 'id_guru']);
    }
}

controllers/RombonganBelajarController.php
<?php

namespace app\controllers;

use Yii;
use app\models\RombonganBelajar;
use app\models\RombonganBelajarSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\Guru;
use app\models\Sekolah;
use app\models\Semester;
use app\models\SiswaSearch;
use app\models\Kelas;
use app\models\Siswa;
use app\models\KelasSearch;
/**
 * RombonganBelajarController implements the CRUD actions for RombonganBelajar model.
 */
class RombonganBelajarController extends Controller
{
    public $layout = "backend.php";
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
            'access' => [
                        'class' => \yii\filters\AccessControl::className(),
                        'only' => ['index','create','update','view'],
                        'rules' => [
                            // allow authenticated users
                            [
                                'allow' => true,
                                'roles' => ['@'],
                            ],
                            // everything else is denied
                        ],
                    ],            
        ];
    }

    /**
     * Lists all RombonganBelajar models.
     * @return mixed
     */
    public function actionIndex()
    {
        if (Yii::$app->user->identity->role=="Administrator") {
            $sekolah = Sekolah::find()->where(['id_user' => Yii::$app->user->identity->id_user])->one();
            $searchModel = new RombonganBelajarSearch(['id_sekolah' => $sekolah->id_sekolah]);
        }elseif (Yii::$app->user->identity->role=="Guru") {
            $guru = Guru::find()->where(['id_user' => Yii::$app->user->identity->id_user])->one();
            $searchModel = new RombonganBelajarSearch(['id_guru' => $guru->id_guru]);
        }else{
            $siswa = Siswa::find()->where(['id_user' => Yii::$app->user->identity->id_user])->one();
            $searchModel = new RombonganBelajarSearch(['id_siswa' => $siswa->id_siswa]);
        }
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionLihatsiswa($id)
    {
        $searchModel = new RombonganBelajarSearch(['id_kelas' => $id]);
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionSudahlulus()
    {
        if(Yii::$app->user->identity->role=="Administrator"){
            $sekolah = Sekolah::find()->where(['id_user' =>  Yii::$app->user->identity->id_user])->one();
            $searchModel = new RombonganBelajarSearch(['id_sekolah' => $sekolah->id_sekolah]);
        }elseif (Yii::$app->user->identity->role=="Guru") {
            $guru = Guru::find()->where(['id_user' => Yii::$app->user->identity->id_user])->one();
            $searchModel = new RombonganBelajarSearch(['id_guru' => $guru->id_guru]);
        }else{
            $siswa = Siswa::find()->where(['id_user' => Yii::$app->user->identity->id_user])->one();
            $searchModel = new RombonganBelajarSearch(['id_kelas' => $siswa->id_kelas]);
        }
        
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('lulus', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    

    public function actionSearch()
    {
        if (Yii::$app->user->identity->role=="Administrator") {
            $sekolah = Sekolah::find()->where(['id_user' => Yii::$app->user->identity->id_user])->one();
            $searchModel = new RombonganBelajarSearch(['id_sekolah' => $sekolah->id_sekolah]);
        }elseif (Yii::$app->user->identity->role=="Guru") {
            $guru = Guru::find()->where(['id_user' => Yii::$app->user->identity->id_user])->one();
            $searchModel = new RombonganBelajarSearch(['id_guru' => $guru->id_guru]);
        }else{
            $siswa = Siswa::find()->where(['id_user' => Yii::$app->user->identity->id_user])->one();
            $searchModel = new RombonganBelajarSearch(['id_siswa' => $siswa->id_siswa]);
        }
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->renderAjax('_search', [
            'model' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionLihatkelas($id)
    {
        $searchModel = new RombonganBelajarSearch(['id_kelas' => $id]);
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    // public function actionSudahlulus()
    // {

    //     $searchModel = SiswaSear
    //     $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

    //     return $this->render('lulus', [
    //         'model' => $searchModel,
    //         'dataProvider' => $dataProvider,
    //     ]);
    // }

    /**
     * Displays a single RombonganBelajar model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->renderAjax('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new RombonganBelajar model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new RombonganBelajar();

        if ($model->load(Yii::$app->request->post())) {
            $sekolah = Sekolah::find()->where(['id_user' =>Yii::$app->user->identity->id_user])->one();
            $guru = Guru::find()->where(['id_user' => Yii::$app->user->identity->id_user])->one();
            if(Yii::$app->user->identity->role=="Administrator"){
                $model->id_sekolah = $sekolah->id_sekolah;
            }else{
                $model->id_sekolah = $guru->id_sekolah;
            }
            $model->save();
            return $this->redirect(['index']);
        }

        return $this->renderAjax('_form', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing RombonganBelajar model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        }

        return $this->renderAjax('_form', [
            'model' => $model,
        ]);
    }

    public function actionAksiNaikKelas(){
        $selection=(array)Yii::$app->request->post('selection');
        if($selection){
            $id_kelas = $_POST['id_kelas'];
        
            foreach ($selection as $key => $value) {
                $model =  new RombonganBelajar();
                $rombel = RombonganBelajar::find()->where(['id_rombel' => $value])->one();
                RombonganBelajar::UpdateAll(['status' => 'Tidak Aktif'],['id_siswa' => $rombel->id_siswa, 'status' => 'Aktif']);
                $kelas = Kelas::find()->where(['id_kelas' => $id_kelas])->one();
                $model->id_sekolah = $rombel->id_sekolah;
                $model->id_kelas = $id_kelas;
                $model->id_siswa = $rombel->id_siswa;
                $model->id_semester = $kelas->id_semester;
                $model->id_guru = $kelas->id_guru;
                $model->tahun_ajaran = $kelas->tahun_ajaran;
                $model->status = "Aktif";
                $model->save();
                $siswa = Siswa::find()->where(['id_siswa' => $model->id_siswa])->one();
                $siswa->id_kelas = $model->id_kelas;
                $siswa->id_semester = $model->id_semester;
                $siswa->id_guru = $model->id_guru;
                $siswa->status = 'Aktif';
                $siswa->save();
            }
        }
        else{
            return "<script>alert('Data Belum Dipilih');
                    window.location = 'index.php?r=rombongan-belajar';
            </script>";
        }
         return $this->redirect(['index']);
    }

    public function actionChoi()
    {
        if ($row = Yii::$app->request->post('test')) {
            foreach ($row as $key => $value) {
                $model =  new RombonganBelajar();
                $rombel = RombonganBelajar::find()->where(['id_rombel' => $value])->one();
                RombonganBelajar::UpdateAll(['status' => 'Tidak Aktif'],['id_siswa' => $rombel->id_siswa, 'status' => 'Aktif']);
                $kelas = Kelas::find()->where(['id_kelas' => $rombel->id_kelas])->one();
                $model->id_sekolah = $rombel->id_sekolah;
                $model->id_kelas = $kelas->id_kelas;
                $model->id_siswa = $rombel->id_siswa;
                $model->id_semester = $kelas->id_semester;
                $model->id_guru = $kelas->id_guru;
                $model->tahun_ajaran = $kelas->tahun_ajaran;
                $model->status = 'Lulus';
                
                $model->save();
                $siswa = Siswa::find()->where(['id_siswa' => $model->id_siswa])->one();
                $siswa->id_kelas = $model->id_kelas;
                $siswa->id_semester = $model->id_semester;

views/rombongan-belajar/_form.php
<?php
use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use kartik\select2\Select2;
use kartik\form\ActiveForm;
use app\models\Siswa;
use app\models\Sekolah;
use app\models\Guru;

/* @var $this yii\web\View */
/* @var $model app\models\RombonganBelajar */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="rombongan-belajar-form">

    <?php $form = ActiveForm::begin(); ?>


     <?= $form->field($model, 'status')->widget(Select2::classname(),[
            'data' => [ 
                'Aktif' => 'Aktif', 
                'Tidak Aktif' => 'Tidak Aktif',
            ],
            'language' => 'de',
            'options' => ['placeholder' => 'Pilih  ...'],
            'pluginOptions' => [
                'allowClear' => true,
                
            ],
        ]) ?>

    <div class="form-group" style="float: right;">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/rombongan-belajar/index.php
<?php

use yii\helpers\Html;
use kartik\grid\GridView;
use yii\helpers\Url;
use app\models\Guru;
use app\models\Kelas;
use app\models\Siswa;
use app\models\BobotPenilaian;
use app\models\RombonganBelajar;
use yii\widgets\ActiveForm;
use app\models\Sekolah;
use yii\helpers\ArrayHelper;
use kartik\select2\Select2;

/* @var $this yii\web\View */
/* @var $searchModel app\models\GuruSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Rombongan Belajar';
$this->params['breadcrumbs'][] = $this->title;
?>
<?= Html::beginForm(['aksi-naik-kelas'], 'post', ['enctype' => 'multipart/form-data']);?>

<?php if(Yii::$app->user->identity->role=="Administrator" || Yii::$app->user->identity->role=="Guru"){?>

    <div class="row" style="margin-left: 4px; margin-right: 4px;">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-body">
                   
                        <?php if(Yii::$app->user->identity->role=="Administrator"){
                            $sekolah = Sekolah::find()->where(['id_user' => Yii::$app->user->identity->id_user])->one();
                        ?>
                            <label>Naik Ke Kelas / Tinggal di Kelas</label>
                            <?= Select2::widget([
                                    'name' => 'id_kelas',
                                    'data' => ArrayHelper::map(Kelas::find()->select(['id_kelas', 'nama' => 'concat(tingkat_kelas, " ", nama)'])->where(['id_sekolah' => $sekolah->id_sekolah])->andWhere(['status' => 'Aktif'])->all(),'id_kelas', 'nama'),
                                    'disabled' => false
                                ]);?>
                        <?php } else { 
                            $guru = Guru::find()->where(['id_user' => Yii::$app->user->identity->id_user])->one();
                        ?>
                            <label>Naik Ke Kelas / Tinggal di Kelas</label>
                            <?= Select2::widget([
                                    'name' => 'id_kelas',
                                    'data' => ArrayHelper::map(Kelas::find()->select(['id_kelas', 'nama' => 'concat(tingkat_kelas, " ", nama)'])->where(['id_sekolah' => $guru->id_sekolah])->andWhere(['status' => 'Aktif'])->all(),'id_kelas', 'nama'),
                                    'disabled' => false
                                ]);?>
                        <?php } ?>

                        <div class="form-group" style="float: right; margin-top: 10px;">
                            <?= Html::submitButton('Simpan', ['class' => 'btn btn-success']) ?>
                        </div>

                </div>
            </div>
        </div>
    </div>
<?php }else { ?>
        <p></p>
<?php } ?>


<section class="content">
      <div class="row">
        <div class="col-xs-12">
          <div class="box">
            
            <!-- /.box-header -->
            <div class="box-body">
                <h2><?= Html::encode($this->title) ;?></h2>
<?php
$gridColumns = [
    ['class' => 'kartik\grid\SerialColumn'],
     
    [
                'attribute' => 'id_siswa',
                'label' => 'Siswa',
                'format' => 'html',
                'value' => function($model){
                    $url = Siswa::find()->where(['id_siswa' => $model->id_siswa])->one()['id_siswa'];
                    $link = Yii::$app->urlManager->createUrl(['siswa/detailsiswa','id' => $url]);
                    return "<a href='".$link."'>".$model->siswa->nama."</a>";
                }
            ],
            [
                'attribute' => 'id_kelas',
                'label' => 'Kelas',
                'format' => 'html',
                'value' => function($model){
                    $url = RombonganBelajar::find()->where(['id_kelas' => $model->id_kelas])->one()['id_kelas'];
                    $link = Yii::$app->urlManager->createUrl(['rombongan-belajar/lihatkelas','id' => $url]);
                    return "<a href='".$link."'>".$model->kelas->tingkat_kelas." ".$model->kelas->nama."</a>";
                }
            ],
             [
                'attribute' => 'id_semester',
                'label' => 'Semester',
                'value' => function($model){
                    return $model->semester->semester;
                }
            ],
            'tahun_ajaran',
            [
                'attribute' => 'id_guru',
                'label' => 'Wali Kelas',
                'value' => function($model){
                    return $model->guru->nama;
                }
            ],
           // 'status',
          
    
    [
        //'class'=>'kartik\grid\BooleanColumn',
        'attribute'=>'status', 
        'vAlign' => 'middle',
        'value' => function($model){
            return $model->status;
        }
    ],
     ['class' => 'yii\grid\ActionColumn',
            'visibleButtons' => [
                'update' => false,
                'delete' => false,
            ],
            'buttons' => [
                  'view' => function($url,$model){
                    
                        $a = Html::button('<span class="fa fa-eye"></span>',
                            ['value' => Url::to(['view','id'=>$model->id_rombel]),
                            'title' => '', 'class' => 'showModalButton btn btn-info']);
                        $b = Html::button('<span class="fa fa-pencil"></span>',
                            ['value' => Url::to(['update','id'=>$model->id_rombel]),
                            'title' => '', 'class' => 'showModalButton btn btn-success']);
                        $c = Html::a('<span class="fa fa-trash"></span>', ['delete', 'id' => $model->id_rombel], [
                                'class' => 'btn btn-danger',
                                'title' => 'Delete',
                                'data' => [
                                    'confirm' => 'Are you sure you want to delete this item?',
                                    'method' => 'post',
                                ],
                                
                                ]) ;
                       
                        if(Yii::$app->user->identity->role=="Administrator" || Yii::$app->user->identity->role=="Guru" ){
                            return $a." ".$c;
                        }else{
                            return $a;
                        }
                        
                    
                        
                    }
            ],
            

    
    ],
    // [
    //     'class' => 'kartik\grid\ActionColumn',
    //     'dropdown' => true,
    //     'vAlign'=>'middle',
    //     'urlCreator' => function($action, $model, $key, $index) {  return '#';  },
    //     'viewOptions'=>[
    //         'title'=>'View', 
    //         'data-toggle'=>'tooltip',
    //     ],
    //     'updateOptions'=>['title'=>'Update', 'data-toggle'=>'tooltip'],
    //     'deleteOptions'=>['title'=>'Delete', 'data-toggle'=>'tooltip'], 
    // ],
    [
        'class' => 'kartik\grid\CheckboxColumn',
    ]
];
    echo GridView::widget([
    'dataProvider' => $dataProvider,
    //'filterModel' => $searchModel,
    'columns' => $gridColumns,        
    'containerOptions' => ['style'=>'overflow: auto'], // only set when $responsive = false
    'beforeHeader'=>[
        [
            'options'=>['class'=>'skip-export'] // remove this row from export
        ]
    ],
    'toolbar' =>  [
         ['content'=>
                Html::button('Search', [
                    'value' => Url::to(['search']), 
                    'class' => 'showModalButton btn btn-default',
                    'style' => 'float:left; margin-right:5px;',
                ]).''.
                Html::a('<span class="fa fa-repeat"></span>', ['index'], ['data-pjax'=>0, 'class' => 'btn btn-default'])
         ],
        '{export}',
        '{toggleData}'
    ],
    'pjax' => true,
    'bordered' => true,
    'striped' => true,
    'condensed' => true,
    'responsive' => true,
    'hover' => true,
    'floatHeader' => true,
   // 'floatHeaderOptions' => ['top' => $scrollingTop],
    'showPageSummary' => true,
    'panel' => [
        'type' => GridView::TYPE_INFO
    ],
]);
?>
</div>
</div>
</div>
</div>
</section>

<?= Html::endForm();?>


<?php
yii\bootstrap\Modal::begin([
'headerOptions' => ['id' => 'modalHeader'],
'id' => 'modal',
'size' => 'modal-default',
'clientOptions' => ['backdrop' => 'static', 'keyboard' => true]
]);
echo "<div id='modalContent'></div>";
 echo '<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>';
yii\bootstrap\Modal::end();
?>

views/rombongan-belajar/lulus.php
<?php
use yii\helpers\Html;
use kartik\grid\GridView;
use yii\helpers\Url;
use yii\bootstrap4\NavBar;
use yii\bootstrap4\Nav;
use kartik\form\ActiveForm;
use app\models\Guru;
use app\models\Siswa;
use app\models\Rangking;
use yii\bootstrap\ButtonDropdown;
use app\models\Sekolah;
use app\models\NilaiAkhir;
use app\models\RombonganBelajar;
/* @var $this yii\web\View */
/* @var $searchModel app\models\GuruSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Rombongan Belajar';
$this->params['breadcrumbs'][] = $this->title;
?>
<section class="content">
      <div class="row">
        <div class="col-xs-12">
        
          <div class="box">
            
            <!-- /.box-header -->
            <div class="box-body">
    <h2><?= Html::encode($this->title) ;?></h2>
   <?php $form = ActiveForm::begin(); ?>
   
<?php
    echo GridView::widget([
    'dataProvider' => $dataProvider,
    //'filterModel' => $searchModel,
     'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            [
                'attribute' => 'id_siswa',
                'label' => 'Siswa',
                'format' => 'html',
                'value' => function($model){
                    $url = Siswa::find()->where(['id_siswa' => $model->id_siswa])->one()['id_siswa'];
                    $link = Yii::$app->urlManager->createUrl(['siswa/detailsiswa','id' => $url]);
                    return "<a href='".$link."'>".$model->siswa->nama."</a>";
                }
            ],
            [
                'attribute' => 'id_kelas',
                'label' => 'Kelas',
                'format' => 'html',
                'value' => function($model){
                    $url = RombonganBelajar::find()->where(['id_kelas' => $model->id_kelas])->one()['id_kelas'];
                    $link = Yii::$app->urlManager->createUrl(['rombongan-belajar/lihatkelas','id' => $url]);
                    return "<a href='".$link."'>".$model->kelas->tingkat_kelas." ".$model->kelas->nama."</a>";
                }
            ],
             [
                'attribute' => 'id_semester',
                'label' => 'Semester',
                'value' => function($model){
                    return $model->semester->semester;
                }
            ],
            'tahun_ajaran',
            [
                'attribute' => 'id_guru',
                'label' => 'Wali Kelas',
                'value' => function($model){
                    return $model->guru->nama;
                }
            ],
           // 'status',
          
    
    [
        //'class'=>'kartik\grid\BooleanColumn',
        'attribute'=>'status', 
        'vAlign' => 'middle',
        'value' => function($model){
            return $model->status;
        }
    ],


            ['class' => 'yii\grid\ActionColumn',
            'visibleButtons' => [
                'update' => false,
                'delete' => false,
            ],
            'buttons' => [
                  'view' => function($url,$model){
                    
                        $a = Html::button('<span class="fa fa-eye"></span>',
                            ['value' => Url::to(['view','id'=>$model->id_rombel]),
                            'title' => '', 'class' => 'showModalButton btn btn-info']);
                        $b = Html::button('<span class="fa fa-pencil"></span>',
                            ['value' => Url::to(['update','id'=>$model->id_rombel]),
                            'title' => '', 'class' => 'showModalButton btn btn-success']);
                        $c = Html::a('<span class="fa fa-trash"></span>', ['delete', 'id' => $model->id_rombel], [
                                'class' => 'btn btn-danger',
                                'title' => 'Delete',
                                'data' => [
                                    'confirm' => 'Are you sure you want to delete this item?',
                                    'method' => 'post',
                                ],
                                
                                ]) ;
                       
                        if(Yii::$app->user->identity->role=="Administrator" || Yii::$app->user->identity->role=="Guru" ){
                            return $a." ".$c;
                        }else{
                            return $a;
                        }
                        
                    
                        
                    }
            ],
            

    
    ],
    [
        'class' => 'kartik\grid\CheckboxColumn',
        'name' => 'test',
    ]
    ],
'containerOptions' => ['style'=>'overflow: auto'], // only set when $responsive = false
'beforeHeader'=>[
    [
        // 'columns'=>[
        //     ['content'=>'Header Before 1', 'options'=>['colspan'=>4, 'class'=>'text-center warning']], 
        //     ['content'=>'Header Before 2', 'options'=>['colspan'=>4, 'class'=>'text-center warning']], 
        //     ['content'=>'Header Before 3', 'options'=>['colspan'=>3, 'class'=>'text-center warning']], 
        // ],
        'options'=>['class'=>'skip-export'] // remove this row from export
    ]
],
'toolbar' =>  [
     ['content'=>
                Html::button('Search', [
                    'value' => Url::to(['search']), 
                    'class' => 'showModalButton btn btn-default',
                    'style' => 'float:left; margin-right:5px;',
                ]).''.
                 Html::a('<span class="fa fa-trash"> Lulus</span>',['choi'],['class' => 'btn btn-default', 'data-confirm' => 'Are you sure you want to delete this item?', 'data-method' => 'POST', 'style' => 'margin-left:5px; margin-right:5px']). ''.
                Html::a('<span class="fa fa-repeat"></span>', ['index'], ['data-pjax'=>0, 'class' => 'btn btn-default'])
     ],
    '{export}',
    '{toggleData}'
],
'pjax' => false,
'bordered' => true,
'striped' => true,
'condensed' => true,
'responsive' => true,
'hover' => true,
'floatHeader' => true,
// 'floatHeaderOptions' => ['top' => $scrollingTop],
'showPageSummary' => true,
'panel' => [
    'type' => GridView::TYPE_INFO
],
]);
?>
 <?php ActiveForm::end(); ?>
</div>
</div>
</div>
</div>
</section>


<?php
yii\bootstrap\Modal::begin([
'headerOptions' => ['id' => 'modalHeader'],
'id' => 'modal',
'size' => 'modal-default',
'clientOptions' => ['backdrop' => 'static', 'keyboard' => true]
]);
echo "<div id='modalContent'></div>";
echo '<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>';
yii\bootstrap\Modal::end();
?>